/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2lab_p2_lisadiazdelvalle;

import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.security.Principal;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author HTS
 */
public class LabExamen2Principal extends javax.swing.JFrame {

    /**
     * Creates new form LabExamen2Principal
     */
    public LabExamen2Principal() {
        initComponents();
        admin Admin = new admin("Deportes.bin");
        Admin.CargarUsuarios();
        deportes = Admin.getDeportes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PMENU_Deporte = new javax.swing.JPopupMenu();
        AgregarDeporte = new javax.swing.JMenuItem();
        JF_AgregarDeporte = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TF_NombreDeporte = new javax.swing.JTextField();
        JB_AgregarDeporte = new javax.swing.JButton();
        PMENU_Torneo = new javax.swing.JPopupMenu();
        AnadirTorneo = new javax.swing.JMenuItem();
        JF_AgregarTorneo = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TF_NombreTorneo = new javax.swing.JTextField();
        JB_AgregarTorne = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CB_PeriodoTorneo = new javax.swing.JComboBox<>();
        JF_AnadirEquipo = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TF_NombreEquipo = new javax.swing.JTextField();
        JB_AgregarEquipo = new javax.swing.JButton();
        PMENU_AgregarEquipo = new javax.swing.JPopupMenu();
        AnadirEquipo = new javax.swing.JMenuItem();
        ListarEquipos = new javax.swing.JMenuItem();
        TablaPosiciones = new javax.swing.JMenuItem();
        CrearPartido = new javax.swing.JMenuItem();
        JD_ListarEquipos = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_Equipos = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JT_VerPartidos = new javax.swing.JTable();
        JB_Verpartidos = new javax.swing.JButton();
        JF_Partido = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        CB_Equipo1 = new javax.swing.JComboBox<>();
        CB_Equipo2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Spiner1 = new javax.swing.JSpinner();
        spinner2 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JB_RegistrarPartido = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        JD_TablaPosiciones = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JT_Posiciones = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        AgregarDeporte.setText("Agregar Deportes");
        AgregarDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDeporteActionPerformed(evt);
            }
        });
        PMENU_Deporte.add(AgregarDeporte);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel2.setText("Agregar Deporte");

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel3.setText("Nombre");

        TF_NombreDeporte.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        JB_AgregarDeporte.setText("Agregar");
        JB_AgregarDeporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarDeporteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_NombreDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(JB_AgregarDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(TF_NombreDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(JB_AgregarDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JF_AgregarDeporteLayout = new javax.swing.GroupLayout(JF_AgregarDeporte.getContentPane());
        JF_AgregarDeporte.getContentPane().setLayout(JF_AgregarDeporteLayout);
        JF_AgregarDeporteLayout.setHorizontalGroup(
            JF_AgregarDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JF_AgregarDeporteLayout.setVerticalGroup(
            JF_AgregarDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AnadirTorneo.setText("Anadir Torneo");
        AnadirTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirTorneoActionPerformed(evt);
            }
        });
        PMENU_Torneo.add(AnadirTorneo);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel4.setText("Agregar Torneo");

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel5.setText("Nombre");

        TF_NombreTorneo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        JB_AgregarTorne.setText("Agregar");
        JB_AgregarTorne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarTorneMouseClicked(evt);
            }
        });
        JB_AgregarTorne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AgregarTorneActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel6.setText("Periodo");

        CB_PeriodoTorneo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        CB_PeriodoTorneo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Q1", "Q2", "Q4", "Q5" }));
        CB_PeriodoTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_PeriodoTorneoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(JB_AgregarTorne, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_NombreTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_PeriodoTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CB_PeriodoTorneo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(TF_NombreTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(JB_AgregarTorne, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout JF_AgregarTorneoLayout = new javax.swing.GroupLayout(JF_AgregarTorneo.getContentPane());
        JF_AgregarTorneo.getContentPane().setLayout(JF_AgregarTorneoLayout);
        JF_AgregarTorneoLayout.setHorizontalGroup(
            JF_AgregarTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JF_AgregarTorneoLayout.setVerticalGroup(
            JF_AgregarTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel7.setText("Agregar Equipo");

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setText("Nombre");

        JB_AgregarEquipo.setText("Agregar");
        JB_AgregarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarEquipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_NombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(JB_AgregarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TF_NombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(JB_AgregarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JF_AnadirEquipoLayout = new javax.swing.GroupLayout(JF_AnadirEquipo.getContentPane());
        JF_AnadirEquipo.getContentPane().setLayout(JF_AnadirEquipoLayout);
        JF_AnadirEquipoLayout.setHorizontalGroup(
            JF_AnadirEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JF_AnadirEquipoLayout.setVerticalGroup(
            JF_AnadirEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AnadirEquipo.setText("Anadir Equipo");
        AnadirEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirEquipoActionPerformed(evt);
            }
        });
        PMENU_AgregarEquipo.add(AnadirEquipo);

        ListarEquipos.setText("Listar Equipos");
        ListarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarEquiposActionPerformed(evt);
            }
        });
        PMENU_AgregarEquipo.add(ListarEquipos);

        TablaPosiciones.setText("Tabla Posiciones");
        TablaPosiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablaPosicionesActionPerformed(evt);
            }
        });
        PMENU_AgregarEquipo.add(TablaPosiciones);

        CrearPartido.setText("Crear Partido\n");
        CrearPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPartidoActionPerformed(evt);
            }
        });
        PMENU_AgregarEquipo.add(CrearPartido);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        JL_Equipos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(JL_Equipos);

        jLabel14.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel14.setText("Listar Equipos");

        JT_VerPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Partidos"
            }
        ));
        jScrollPane3.setViewportView(JT_VerPartidos);

        JB_Verpartidos.setText("-->");
        JB_Verpartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_VerpartidosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_Verpartidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(JB_Verpartidos)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_ListarEquiposLayout = new javax.swing.GroupLayout(JD_ListarEquipos.getContentPane());
        JD_ListarEquipos.getContentPane().setLayout(JD_ListarEquiposLayout);
        JD_ListarEquiposLayout.setHorizontalGroup(
            JD_ListarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_ListarEquiposLayout.setVerticalGroup(
            JD_ListarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel9.setText("Equipo 1");

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel10.setText("Equipo 2");

        jLabel11.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel11.setText("Puntos Equipo 1");

        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel12.setText("Puntos Equipo 2");

        JB_RegistrarPartido.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JB_RegistrarPartido.setText("Registrar");
        JB_RegistrarPartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_RegistrarPartidoMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel13.setText("Partido");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CB_Equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spiner1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CB_Equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(JB_RegistrarPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_Equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_Equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spiner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(JB_RegistrarPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout JF_PartidoLayout = new javax.swing.GroupLayout(JF_Partido.getContentPane());
        JF_Partido.getContentPane().setLayout(JF_PartidoLayout);
        JF_PartidoLayout.setHorizontalGroup(
            JF_PartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JF_PartidoLayout.setVerticalGroup(
            JF_PartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        JT_Posiciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Posicion", "Equipo", "Puntaje"
            }
        ));
        jScrollPane4.setViewportView(JT_Posiciones);

        jLabel15.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel15.setText("Tabla de Posiciones");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel15))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_TablaPosicionesLayout = new javax.swing.GroupLayout(JD_TablaPosiciones.getContentPane());
        JD_TablaPosiciones.getContentPane().setLayout(JD_TablaPosicionesLayout);
        JD_TablaPosicionesLayout.setHorizontalGroup(
            JD_TablaPosicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_TablaPosicionesLayout.setVerticalGroup(
            JD_TablaPosicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel1.setText("Examen II");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Torneos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q4");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q5");
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        if (evt.getButton() == 3) {
            int row = jTree1.getClosestRowForLocation(evt.getX(), evt.getY());
            jTree1.setSelectionRow(row);
            Object v1 = jTree1.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() == "Torneos") {
                PMENU_Deporte.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (nodo_seleccionado.getUserObject() instanceof Deporte) {
                PMENU_Torneo.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (nodo_seleccionado.getUserObject() instanceof Torneo) {
                PMENU_AgregarEquipo.show(evt.getComponent(), evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_jTree1MouseClicked

    private void JB_AgregarDeporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarDeporteMouseClicked

        try {
            Deporte d = new Deporte(TF_NombreDeporte.getText());
            deportes.add(d);
            admin admin = new admin("Deportes.bin");
            admin.setDeportes(deportes);
            try {
                admin.escribirUsuarios();
            } catch (IOException ex) {

            }
            DefaultTreeModel modelo = (DefaultTreeModel) jTree1.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();

            DefaultMutableTreeNode nodoNombre = null;

            for (int i = 0; i < raiz.getChildCount(); i++) {
                nodoNombre = (DefaultMutableTreeNode) raiz.getChildAt(i);
                DefaultMutableTreeNode deporte = new DefaultMutableTreeNode(d);
                nodoNombre.add(deporte);
            }

            raiz.add(nodoNombre);
            modelo.reload();
            TF_NombreDeporte.setText("");

            JOptionPane.showMessageDialog(this, "Deporte agregado exitosamente");
            JF_AgregarDeporte.setVisible(false);
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_JB_AgregarDeporteMouseClicked

    private void AgregarDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDeporteActionPerformed
        this.setVisible(false);
        JF_AgregarDeporte.pack();
        JF_AgregarDeporte.setLocationRelativeTo(this);
        JF_AgregarDeporte.setVisible(true);
    }//GEN-LAST:event_AgregarDeporteActionPerformed

    private void AnadirTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirTorneoActionPerformed
        deporteseleccionado = nodo_seleccionado.getUserObject().toString();
        this.setVisible(false);
        JF_AgregarTorneo.pack();
        JF_AgregarTorneo.setLocationRelativeTo(this);
        JF_AgregarTorneo.setVisible(true);
    }//GEN-LAST:event_AnadirTorneoActionPerformed

    private void JB_AgregarTorneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarTorneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_AgregarTorneMouseClicked

    private void JB_AgregarTorneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AgregarTorneActionPerformed
        try {
            Torneo d = new Torneo(TF_NombreTorneo.getText());
            torneos.add(d);
            DefaultTreeModel modelo = (DefaultTreeModel) jTree1.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();

            DefaultMutableTreeNode nodoNombre = null;

            for (int i = 0; i < raiz.getChildCount(); i++) {
                nodoNombre = (DefaultMutableTreeNode) raiz.getChildAt(i);
                if (nodoNombre.getUserObject().equals(CB_PeriodoTorneo.getSelectedItem().toString())) {
                    for (int j = 0; j < nodoNombre.getChildCount(); j++) {
                        DefaultMutableTreeNode deporte = (DefaultMutableTreeNode) nodoNombre.getChildAt(j);
                        if (deporteseleccionado.equals(deporte.getUserObject().toString())) {
                            DefaultMutableTreeNode torneo = new DefaultMutableTreeNode(d);
                            deporte.add(torneo);
                            nodoNombre.add(deporte);
                            for (int k = 0; k < deportes.size(); k++) {
                                Deporte dep = deportes.get(k);
                                if (dep.getNombre().equals(deporte.getUserObject().toString())) {
                                    dep.getTorneos().add(d);
                                }

                            }
                            break;
                        }
                    }

                }
            }
            admin admin = new admin("Deportes.bin");
            admin.setDeportes(deportes);
            try {
                admin.escribirUsuarios();
            } catch (IOException ex) {

            }

            raiz.add(nodoNombre);
            modelo.reload();
            TF_NombreTorneo.setText("");

            JOptionPane.showMessageDialog(this, "Torneo agregado exitosamente");
            JF_AgregarTorneo.setVisible(false);
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_JB_AgregarTorneActionPerformed

    private void AnadirEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirEquipoActionPerformed
        deporteseleccionado = nodo_seleccionado.getUserObject().toString();
        this.setVisible(false);
        JF_AnadirEquipo.pack();
        JF_AnadirEquipo.setLocationRelativeTo(this);
        JF_AnadirEquipo.setVisible(true);
    }//GEN-LAST:event_AnadirEquipoActionPerformed

    private void JB_AgregarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarEquipoMouseClicked
        try {
            Equipo e = new Equipo(TF_NombreEquipo.getText(), 0);
            for (Deporte d : deportes) {
                for (int i = 0; i < d.getTorneos().size(); i++) {
                    if (d.getTorneos().get(i).getNombre().equals(deporteseleccionado)) {
                        d.getTorneos().get(i).getEquipos().add(e);
                        JOptionPane.showMessageDialog(this, "Equipo Anadido exitosamente");
                    }
                }

            }
            admin admin = new admin("Deportes.bin");
            admin.setDeportes(deportes);
            try {
                admin.escribirUsuarios();
            } catch (IOException ex) {

            }
            TF_NombreEquipo.setText("");
            JF_AnadirEquipo.setVisible(false);
            this.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_JB_AgregarEquipoMouseClicked

    private void ListarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarEquiposActionPerformed
        this.setVisible(false);
        JD_ListarEquipos.pack();
        JD_ListarEquipos.setLocationRelativeTo(this);
        JD_ListarEquipos.setVisible(true);
        DefaultListModel modelo = (DefaultListModel) JL_Equipos.getModel();

        String torneo = nodo_seleccionado.getUserObject().toString();
        for (Deporte d : deportes) {
            for (int i = 0; i < d.getTorneos().size(); i++) {
                if (d.getTorneos().get(i).getNombre().equals(torneo)) {
                    for (int j = 0; j < d.getTorneos().get(i).getEquipos().size(); j++) {
                        Equipo e = d.getTorneos().get(i).getEquipos().get(j);
                        modelo.addElement(e.getNombre());

                    }
                }

            }
        }

    }//GEN-LAST:event_ListarEquiposActionPerformed

    private void CB_PeriodoTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_PeriodoTorneoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_PeriodoTorneoActionPerformed

    private void CrearPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPartidoActionPerformed
        deporteseleccionado = nodo_seleccionado.getUserObject().toString();
        this.setVisible(false);
        JF_Partido.pack();
        JF_Partido.setLocationRelativeTo(this);
        JF_Partido.setVisible(true);
        llenarcomboEquipo1();
        llenarcomboEquipo2();
    }//GEN-LAST:event_CrearPartidoActionPerformed

    private void JB_RegistrarPartidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_RegistrarPartidoMouseClicked
        try {
            int puntos1 = 0;
            int puntos2 = 0;
            Partido p = new Partido(CB_Equipo1.getSelectedItem().toString(), CB_Equipo2.getSelectedItem().toString(), ((Integer) Spiner1.getValue()), ((Integer) spinner2.getValue()));
            for (Deporte d : deportes) {
                for (int i = 0; i < d.getTorneos().size(); i++) {
                    if (d.getTorneos().get(i).getNombre().equals(deporteseleccionado)) {
                        d.getTorneos().get(i).getPartidos().add(p);

                        JOptionPane.showMessageDialog(this, "Partido Registrado exitosamente");
                    }
                }

            }

            for (Deporte d : deportes) {
                for (int i = 0; i < d.getTorneos().size(); i++) {
                    if (d.getTorneos().get(i).getNombre().equals(deporteseleccionado)) {
                        if (d.getTorneos().get(i).getEquipos().get(i).getNombre().equals(CB_Equipo1.getSelectedItem().toString())) {
                            puntos1 = ((Integer) Spiner1.getValue());
                            int e1 = d.getTorneos().get(i).getEquipos().get(i).getPuntos();
                            d.getTorneos().get(i).getEquipos().get(i).setPuntos(e1 + puntos1);
                            System.out.println(d.getTorneos().get(i).getEquipos().get(i).getPuntos());

                        }
                    }

                }
            }
            for (Deporte d : deportes) {
                for (int i = 0; i < d.getTorneos().size(); i++) {
                    if (d.getTorneos().get(i).getNombre().equals(deporteseleccionado)) {
                        if (d.getTorneos().get(i).getEquipos().get(i).getNombre().equals(CB_Equipo2.getSelectedItem().toString())) {
                            puntos2 = ((Integer) spinner2.getValue());
                            int e2 = d.getTorneos().get(i).getEquipos().get(i).getPuntos();
                            System.out.println(e2);

                            d.getTorneos().get(i).getEquipos().get(i).setPuntos(e2 + puntos2);
                            System.out.println(d.getTorneos().get(i).getEquipos().get(i).getPuntos());
                        }
                    }

                }
            }
            admin admin = new admin("Deportes.bin");
            admin.setDeportes(deportes);
            try {
                admin.escribirUsuarios();
            } catch (IOException ex) {

            }
            Spiner1.setValue(0);
            spinner2.setValue(0);
            JF_Partido.setVisible(false);
            this.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JB_RegistrarPartidoMouseClicked

    private void JB_VerpartidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_VerpartidosMouseClicked
        try {

            //limpiar tabla
            JT_VerPartidos.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{
                "Partidos"}));
            //JL_Equipos.get

            String torneo = nodo_seleccionado.getUserObject().toString();
            DefaultListModel m = (DefaultListModel) JL_Equipos.getModel();

            for (Deporte d : deportes) {
                for (int i = 0; i < d.getTorneos().size(); i++) {
                    if (d.getTorneos().get(i).getNombre().equals(torneo)) {
                        for (int j = 0; j < d.getTorneos().get(i).getEquipos().size(); j++) {
                            Equipo e = d.getTorneos().get(i).getEquipos().get(j);
                           // System.out.println(e);
                           // System.out.println(m.getElementAt(JL_Equipos.getSelectedIndex()).toString());
                            if (m.getElementAt(JL_Equipos.getSelectedIndex()).equals(e)) {
                                
                                Partido p = d.getTorneos().get(i).getPartidos().get(j);
                                Object[] row = {p.toString()};
                                DefaultTableModel modelo = (DefaultTableModel) JT_VerPartidos.getModel();
                                modelo.addRow(row);
                                JT_VerPartidos.setModel(modelo);
                            }
                        }

                    }
                }

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_JB_VerpartidosMouseClicked

    private void TablaPosicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablaPosicionesActionPerformed
        this.setVisible(true);
        JD_TablaPosiciones.pack();
        JD_TablaPosiciones.setLocationRelativeTo(this);
        JD_TablaPosiciones.setVisible(true);
        try {
            int index = 1;
            //limpiar tabla
            JT_Posiciones.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{
                "Posicion", "Equipo", "Puntos"}));
            String torneo = nodo_seleccionado.getUserObject().toString();
            for (Deporte d : deportes) {
                for (int i = 0; i < d.getTorneos().size(); i++) {
                    if (d.getTorneos().get(i).getNombre().equals(torneo)) {
                        for (int j = 0; j < d.getTorneos().get(i).getEquipos().size(); j++) {
                            Equipo e = d.getTorneos().get(i).getEquipos().get(j);
                            Object[] row = {index, e.getNombre(), e.getPuntos()};
                            index++;
                            DefaultTableModel modelo = (DefaultTableModel) JT_Posiciones.getModel();
                            modelo.addRow(row);
                            JT_Posiciones.setModel(modelo);
                        }
                    }
                }

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_TablaPosicionesActionPerformed

    private void llenarcomboEquipo1() {
        CB_Equipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        String torneo = nodo_seleccionado.getUserObject().toString();
        for (Deporte d : deportes) {
            for (int i = 0; i < d.getTorneos().size(); i++) {
                if (d.getTorneos().get(i).getNombre().equals(torneo)) {
                    for (int j = 0; j < d.getTorneos().get(i).getEquipos().size(); j++) {
                        Equipo e = d.getTorneos().get(i).getEquipos().get(j);
                        DefaultComboBoxModel modelo
                                = (DefaultComboBoxModel) CB_Equipo1.getModel();
                        modelo.addElement(e.getNombre());
                        CB_Equipo1.setModel(modelo);
                    }
                }

            }
        }
    }

    private void llenarcomboEquipo2() {
        CB_Equipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        String torneo = nodo_seleccionado.getUserObject().toString();
        for (Deporte d : deportes) {
            for (int i = 0; i < d.getTorneos().size(); i++) {
                if (d.getTorneos().get(i).getNombre().equals(torneo)) {
                    for (int j = 0; j < d.getTorneos().get(i).getEquipos().size(); j++) {
                        Equipo e = d.getTorneos().get(i).getEquipos().get(j);
                        DefaultComboBoxModel modelo
                                = (DefaultComboBoxModel) CB_Equipo2.getModel();
                        modelo.addElement(e.getNombre());
                        CB_Equipo2.setModel(modelo);
                    }
                }

            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabExamen2Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabExamen2Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabExamen2Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabExamen2Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabExamen2Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarDeporte;
    private javax.swing.JMenuItem AnadirEquipo;
    private javax.swing.JMenuItem AnadirTorneo;
    private javax.swing.JComboBox<String> CB_Equipo1;
    private javax.swing.JComboBox<String> CB_Equipo2;
    private javax.swing.JComboBox<String> CB_PeriodoTorneo;
    private javax.swing.JMenuItem CrearPartido;
    private javax.swing.JButton JB_AgregarDeporte;
    private javax.swing.JButton JB_AgregarEquipo;
    private javax.swing.JButton JB_AgregarTorne;
    private javax.swing.JButton JB_RegistrarPartido;
    private javax.swing.JButton JB_Verpartidos;
    private javax.swing.JDialog JD_ListarEquipos;
    private javax.swing.JDialog JD_TablaPosiciones;
    private javax.swing.JFrame JF_AgregarDeporte;
    private javax.swing.JFrame JF_AgregarTorneo;
    private javax.swing.JFrame JF_AnadirEquipo;
    private javax.swing.JFrame JF_Partido;
    private javax.swing.JList<String> JL_Equipos;
    private javax.swing.JTable JT_Posiciones;
    private javax.swing.JTable JT_VerPartidos;
    private javax.swing.JMenuItem ListarEquipos;
    private javax.swing.JPopupMenu PMENU_AgregarEquipo;
    private javax.swing.JPopupMenu PMENU_Deporte;
    private javax.swing.JPopupMenu PMENU_Torneo;
    private javax.swing.JSpinner Spiner1;
    private javax.swing.JTextField TF_NombreDeporte;
    private javax.swing.JTextField TF_NombreEquipo;
    private javax.swing.JTextField TF_NombreTorneo;
    private javax.swing.JMenuItem TablaPosiciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTree jTree1;
    private javax.swing.JSpinner spinner2;
    // End of variables declaration//GEN-END:variables
//Personajes selectedPersonaje;
    String deporteseleccionado;
    ArrayList<Deporte> deportes = new ArrayList();
    ArrayList<Torneo> torneos = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;

}
